FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /app
COPY . /app/
RUN dotnet dev-certs https

#run a build at this stage to detect issues earlier.
RUN dotnet build


# Explicitly ask for path to be added
ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool install --global dotnet-ef

# commented out below to change the entrypoint to a shell script. 
# this is to ensure dotnet db update got run at the right timing.
# ENV ASPNETCORE_URLS=https://*:5002
# CMD dotnet watch run

RUN chmod +x dev-entrypoint.sh
CMD /bin/bash dev-entrypoint.sh

# use this if ASPNETCORE_URLS was ignored
# CMD dotnet run --urls https://0.0.0.0:5002
